#!/usr/bin/env python3
# mcuboot の DFU 表示 LED を WS2812 (アドレサブル LED) に対応させる。
#
# 背景: mcuboot 標準の INDICATION_LED は gpio-leds を前提に GPIO を
# ベタに High/Low するだけなので、単線シリアル時系列を要求する WS2812 は
# まったく光らない (実測: 54L/52840 とも DFU 中は消灯のまま)。
# LED が唯一の状態表示手段になるモジュール (USB なし・画面なし) では、
# 「bootloader に留まっている」ことが見えないのは実用上つらい。
#
# 対処: mcuboot 側にも Zephyr の ws2812-spi ドライバを載せ、
# io_led_init/io_led_set を led_strip API 実装に差し替える。
# ビットバングではなく SPI ハードウェアが時系列を作るので、
# コンパイラ最適化やクロック差 (52840 64MHz / 54L 128MHz) に影響されない。
#
# DT ノード (spi + ws2812 + led-strip alias) と Kconfig は
# gen_mcuboot_files.py が mcuboot.overlay / mcuboot.conf に出力する。
# それらが無いビルド (LED 無し・単色 LED) では何も変更しない。
#
# 実行場所: zephyr-workspace/SlimeVR-Tracker-nRF (patch_mcuboot_pwr.py と同じ)
import os, sys

CANDIDATES = (
    "../bootloader/mcuboot/boot/zephyr/io.c",
    "../modules/mcuboot/boot/zephyr/io.c",
)

path = sys.argv[1] if len(sys.argv) > 1 else next(
    (p for p in CANDIDATES if os.path.isfile(p)), None)
if not path or not os.path.isfile(path):
    sys.exit("patch_mcuboot_ws2812: mcuboot io.c not found: " + ", ".join(CANDIDATES))

MARK = "SLIMENRF_WS2812_LED"
s = open(path, encoding="utf-8", newline="").read()
NL = "\r\n" if "\r\n" in s else "\n"
if MARK in s:
    print(f"patch_mcuboot_ws2812: already applied ({path})")
    sys.exit(0)

OLD = """#if DT_NODE_EXISTS(DT_ALIAS(mcuboot_led0))
#define LED0_NODE DT_ALIAS(mcuboot_led0)
#endif

#if DT_NODE_HAS_STATUS(LED0_NODE, okay) && DT_NODE_HAS_PROP(LED0_NODE, gpios)
static const struct gpio_dt_spec led0 = GPIO_DT_SPEC_GET(LED0_NODE, gpios);
#else
/* A build error here means your board isn't set up to drive an LED. */
#error "Unsupported board: led0 devicetree alias is not defined"
#endif

BOOT_LOG_MODULE_DECLARE(mcuboot);

void io_led_init(void)
{
    if (!device_is_ready(led0.port)) {
        BOOT_LOG_ERR("Didn't find LED device referred by the LED0_NODE\\n");
        return;
    }

    gpio_pin_configure_dt(&led0, GPIO_OUTPUT);
    gpio_pin_set_dt(&led0, 0);
}

void io_led_set(int value)
{
    gpio_pin_set_dt(&led0, value);
}
"""

NEW = """/* ==== """ + MARK + """ (SlimeNRF-Web-Builder) ====
 * WS2812 (addressable) LED support: the stock implementation only drives a
 * plain GPIO, which an addressable LED ignores completely. When the build
 * provides a led-strip alias we use the ws2812 driver instead, so the strict
 * single-wire timing is generated by SPI hardware rather than by bit-banging.
 * DFU indication colour is a dim purple (distinct from any app pattern). */
#if DT_NODE_EXISTS(DT_ALIAS(led_strip))
#define """ + MARK + """ 1
#include <zephyr/drivers/led_strip.h>

BOOT_LOG_MODULE_DECLARE(mcuboot);

static const struct device *const slimenrf_strip = DEVICE_DT_GET(DT_ALIAS(led_strip));

void io_led_init(void)
{
    if (!device_is_ready(slimenrf_strip)) {
        BOOT_LOG_ERR("WS2812 strip not ready\\n");
    }
}

void io_led_set(int value)
{
    struct led_rgb px = { .r = 0, .g = 0, .b = 0 };

    if (!device_is_ready(slimenrf_strip)) {
        return;
    }
    if (value) {
        px.r = 24;
        px.b = 24;  /* dim purple = "in bootloader / serial recovery" */
    }
    (void)led_strip_update_rgb((struct device *)slimenrf_strip, &px, 1);
}

#else /* no led-strip alias: stock gpio-leds implementation */

#if DT_NODE_EXISTS(DT_ALIAS(mcuboot_led0))
#define LED0_NODE DT_ALIAS(mcuboot_led0)
#endif

#if DT_NODE_HAS_STATUS(LED0_NODE, okay) && DT_NODE_HAS_PROP(LED0_NODE, gpios)
static const struct gpio_dt_spec led0 = GPIO_DT_SPEC_GET(LED0_NODE, gpios);
#else
/* A build error here means your board isn't set up to drive an LED. */
#error "Unsupported board: led0 devicetree alias is not defined"
#endif

BOOT_LOG_MODULE_DECLARE(mcuboot);

void io_led_init(void)
{
    if (!device_is_ready(led0.port)) {
        BOOT_LOG_ERR("Didn't find LED device referred by the LED0_NODE\\n");
        return;
    }

    gpio_pin_configure_dt(&led0, GPIO_OUTPUT);
    gpio_pin_set_dt(&led0, 0);
}

void io_led_set(int value)
{
    gpio_pin_set_dt(&led0, value);
}

#endif /* DT_NODE_EXISTS(DT_ALIAS(led_strip)) */
"""

o = OLD.replace("\n", NL)
n = NEW.replace("\n", NL)
if o not in s:
    sys.exit("patch_mcuboot_ws2812: FAILED, io.c LED block anchor not found")
s = s.replace(o, n, 1)
open(path, "w", encoding="utf-8", newline="").write(s)
print(f"patch_mcuboot_ws2812: applied ({path})")
